src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\Column(type="text")
     */
    private $Contenu;

    /**
     * @ORM\Column(type="date")
     */
    private $dateCreation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $NomAuteurAssocie;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $CategorieAssocie;

    /**
     * @ORM\Column(type="integer")
     */
    private $NombreVues;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->Contenu;
    }

    public function setContenu(string $Contenu): self
    {
        $this->Contenu = $Contenu;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): self
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getNomAuteurAssocie(): ?string
    {
        return $this->NomAuteurAssocie;
    }

    public function setNomAuteurAssocie(string $NomAuteurAssocie): self
    {
        $this->NomAuteurAssocie = $NomAuteurAssocie;

        return $this;
    }

    public function getCategorieAssocie(): ?string
    {
        return $this->CategorieAssocie;
    }

    public function setCategorieAssocie(string $CategorieAssocie): self
    {
        $this->CategorieAssocie = $CategorieAssocie;

        return $this;
    }

    public function getNombreVues(): ?int
    {
        return $this->NombreVues;
    }

    public function setNombreVues(int $NombreVues): self
    {
        $this->NombreVues = $NombreVues;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    /**
     * @Route("/login", name="app_login")
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('target_path');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    /**
     * @Route("/logout", name="app_logout")
     */
    public function logout()
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

src/Controller/firstAppController.php
<?php 

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Article;
use App\Service\swearCleaner;

class firstAppController extends AbstractController
{
    /** 
     * @Route("/", name="index")
     */
    public function index(): Response
    {
        $articleRepository = $this->getDoctrine()->getRepository(Article::class);
        $articles = $articleRepository->findAll();

        return $this->render('firstApp/index.html.twig', [
            'articles' => $articles,
        ]);
    }

    /**
     * @Route("/article/{id}", name="single",requirements={"id"="\d+"})
     */

    public function single(int $id): Response
    {
        $articleRepository = $this->getDoctrine()->getRepository(Article::class);
        $article = $articleRepository->find($id);
        $articleDate = $article->getDateCreation()->format("d/m/Y");

        // $swearCleaner = new SwearCleaner();

        // $article = $swearCleaner->cleanSwear($article);

        return $this->render('firstApp/single.html.twig', [
            'article' => $article,
            'date' => $articleDate,
        ]);
    }

    /**
     * @Route("/admin/article/add", name="add")
     */
    public function add(): Response
    {
        return $this->render('firstApp/adminAdd.html.twig');
    }

        /**
     * @Route("/createAccount", name="createAccount")
     */
    public function createAccount(): Response
    {
        return $this->render('firstApp/addAccount.html.twig');
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}
            <ul class="nav  mt-0">
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{{ path("index")}}">Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{{ path("add")}}">Ajouter un article</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link text-dark" href="{{ path("app_login")}}">Se Connecter</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link text-dark" href="{{ path("createAccount")}}">Créer un compte</a>
                </li>
            </ul>
                <header class="jumbotron jumbotron-fluid bg-dark text-white">
                    <section class="container">
                        <h1 class="display-4">Exercices Symfony</h1>
                        <p class="lead">J'essaye des choses</p>
                    </section>
                </header>

                <main class="container my-5">
                    {% block main %}  {% endblock %}
                </main>

                <footer class="jumbotron jumbotron-fluid bg-dark text-white">
                    <section class="container">
                        <p class="lead">Tout droit réservés</p>
                    </section>
                </footer>
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/firstApp/addAccount.html.twig
{% extends "base.html.twig" %}
{% block title %} Création de compte {% endblock %}
{% block main %}
<h2>Vous prouvez créer un compte</h2>
{% endblock %}

templates/firstApp/adminAdd.html.twig
{% extends "base.html.twig" %}
{% block title %} Accueil {% endblock %}
{% block main %}
<h2>Vous prouvez créer un article</h2>
{% endblock %}

templates/firstApp/connection.html.twig
{% extends "base.html.twig" %}
{% block title %} Connection {% endblock %}
{% block main %}
<h2>Vous prouvez vous connecter</h2>
{% endblock %}

templates/firstApp/index.html.twig
{% extends "base.html.twig" %}
{% block title %} Accueil {% endblock %}
{% block main %}
<h2>Les articles disponnible</h2>
{% for article in articles %}
        <div class="card my-3">
            <div class="card-body">
                <h5 class="card-title">{{article.titre}}</h5>
                <p class="card-text">{{article.nomAuteurAssocie}}<p>
                <a href="{{ path('single',{'id':article.id}) }}" class="btn btn-secondary">Voir</a>
            </div>
        </div>
{% endfor %}
{% endblock %}

templates/firstApp/single.html.twig
{% extends "base.html.twig" %}
{% block title %} Accueil {% endblock %}
{% block main %}
<h2>Article numéros {{(article.id)-1}} </h2>
<div class="card my-3">
    <div class="card-body">
        <h5 class="card-title">{{article.titre}}</h5>
        <p class="card-text">{{article.contenu}}<p>
        <p class="card-text">écrit par {{article.nomAuteurAssocie}}<p>
        <p class="card-text">{{article.nombreVues}} vues<p>
        <p class="card-text">posté le : {{date}}<p>
    </div>
</div>
{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}
<form method="post">
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    {% if app.user %}
        <div class="mb-3">
            You are logged in as {{ app.user.username }}, <a href="{{ path('app_logout') }}">Logout</a>
        </div>
    {% endif %}

    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <label for="inputUsername">Username</label>
    <input type="text" value="{{ last_username }}" name="username" id="inputUsername" class="form-control" required autofocus>
    <label for="inputPassword">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control" required>

    <input type="hidden" name="_csrf_token"
           value="{{ csrf_token('authenticate') }}"
    >

    {#
        Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
        See https://symfony.com/doc/current/security/remember_me.html

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" name="_remember_me"> Remember me
            </label>
        </div>
    #}

    <button class="btn btn-lg btn-primary" type="submit">
        Sign in
    </button>
</form>
{% endblock %}